// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BaseResp struct {
	StatusCode int64  `json:"status_code"`
	StatusMsg  string `json:"status_msg,optional"`
}

type CaptchaReq struct {
	Email string `json:"email"`
}

type CaptchaResp struct {
	BaseResp
}

type ChatHistoryReq struct {
	SessionId string `json:"sessionId"`
}

type ChatHistoryResp struct {
	BaseResp
	History []HistoryItem `json:"history,optional"`
}

type ChatQuestionReq struct {
	Question  string `json:"question"`
	ModelType string `json:"modelType"`
}

type ChatSendReq struct {
	Question  string `json:"question"`
	ModelType string `json:"modelType"`
	SessionId string `json:"sessionId"`
}

type ChatSendResp struct {
	BaseResp
	Information string `json:"Information,optional"`
}

type CreateSessionAndSendMessageResp struct {
	BaseResp
	Information string `json:"Information,optional"`
	SessionId   string `json:"sessionId,optional"`
}

type GetUserSessionsResp struct {
	BaseResp
	Sessions []SessionInfo `json:"sessions,optional"`
}

type HistoryItem struct {
	IsUser  bool   `json:"is_user"`
	Content string `json:"content"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	BaseResp
	Token string `json:"token,optional"`
}

type RecognizeImageResp struct {
	BaseResp
	ClassName string `json:"class_name,optional"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Captcha  string `json:"captcha"`
	Password string `json:"password"`
}

type RegisterResp struct {
	BaseResp
	Token string `json:"token,optional"`
}

type SessionInfo struct {
	SessionId string `json:"sessionId"`
	Name      string `json:"name"`
}

type UploadFileResp struct {
	BaseResp
	FilePath string `json:"file_path,optional"`
}
