// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	chat "SamaraAI/internal/handler/chat"
	user "SamaraAI/internal/handler/user"
	"SamaraAI/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/chat/history",
					Handler: chat.ChatHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/chat/send",
					Handler: chat.ChatSendHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/chat/send-new-session",
					Handler: chat.CreateSessionAndSendMessageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/chat/sessions",
					Handler: chat.GetUserSessionsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/AI"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/captcha",
				Handler: user.CaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
